version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
#    volumes:
#      - "./data:/kafka"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.17.0.1:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092
    depends_on:
      - zookeeper
    restart: always
