version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.108
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    depends_on:
      - zookeeper
    restart: always

  kafka-manager:  
    image: sheepkiller/kafka-manager  ## 镜像：开源的web管理kafka集群的界面
    ports:  
      - "9000:9000"                   ## 端口映射
    environment:
      ZK_HOSTS: 192.168.1.108         ## 宿主机IP
    restart: always
