version: '3'

services:
  emqx:
    image: emqx/emqx
    ports:
      - "1883:1883"
      - "8801:8801"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    restart: always
